# Generated by Django 3.1.4 on 2021-01-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20201210_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
