# Generated by Django 3.1.4 on 2020-12-17 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_auto_20201210_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('blocked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentReminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('telephone', 'Telephone')], max_length=9)),
                ('reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
            ],
            options={
                'verbose_name_plural': 'Appointment Reminders',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appointment.slot'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
