# Generated by Django 3.1.4 on 2020-12-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.IntegerField()),
                ('message_body', models.CharField(max_length=160)),
                ('reminder_date', models.DateField()),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
